In [2]:
import numpy as np

# Exercise: Data Collection and Analysis

Let's create some data! Make a variable called **reaction_times** containing a list of 15 reactrion time samples from this experiment:  https://humanbenchmark.com/tests/reactiontime


In [1]:
reaction_times = [598, 346, 320, 265, 281, 281, 297, 394, 321, 298, 264, 334, 260, 279, 249]    # Your Data Goes here

#### Analysis Questions

Were your reaction times quick on average?  Let's check the mean of your reaction times.

In [3]:
np.mean(reaction_times)

319.1333333333333

Did your reaction times vary a lot?  Let's check the standard deviation of your reaction time data.

In [4]:
np.std(reaction_times)

83.3305599538502

Did your reaction times improve or worsen over the course of the experiment?  Let's check the correlation of your reaction time data

In [7]:
np.corrcoef(reaction_times)

1.0

## Data Export/Import

Let's compare our reaction times to someone else!  Export your list of reaction times to a text file, to give to your partner.

In [9]:
data = [598, 346, 320, 265, 281, 281, 297, 394, 321, 298, 264, 334, 260, 279, 249]  # replace this with your data
np.savetxt("reaction_times_kilian.txt", data)

Trade files with your partner and load their data

In [10]:
reaction_times2 = np.loadtxt("reaction_times_vera.txt")

In [13]:
reaction_times3 = np.loadtxt("reaction_times_paula.txt")

### Can you reproduce their results?  

Were their reaction times quick on average?  Let's check the mean of their reaction times.

In [12]:
np.mean(reaction_times2)


array([437., 392., 438., 336., 396., 361., 354., 330., 366., 414., 449.,
       383., 398., 372., 410.])

In [14]:
np.mean(reaction_times3)

2111.266666666667

Did their reaction times vary a lot?  Let's check the standard deviation of their reaction time data.

In [15]:
np.std(reaction_times2)

35.27315630271206

In [16]:
np.std(reaction_times3)

4868.425227479164

Did their reaction times improve or worsen over the course of the experiment?  Let's check the correlation of their reaction time data

Did your reaction times differ significantly between you and your partner?  Let's check using a t-test and see if the t-statistic is high and the p-value is low.

Example Code:  

```python
from scipy import stats
stats.ttest_ind([1, 2, 3], [2, 3, 4])  
```

In [24]:
from scipy import stats

In [18]:
stats.ttest_ind(reaction_times, reaction_times2)

Ttest_indResult(statistic=-2.8917091908720267, pvalue=0.007329842509280796)

In [19]:
stats.ttest_ind(reaction_times, reaction_times3)

Ttest_indResult(statistic=-1.3771530928045947, pvalue=0.1793758008564157)

What other statistics functions are in the scipy.stats module?  Explore the module (documaentation here: https://docs.scipy.org/doc/scipy/reference/stats.html) and  calculate 3 other statistics on the data you have:

In [20]:
reaction_times

[598, 346, 320, 265, 281, 281, 297, 394, 321, 298, 264, 334, 260, 279, 249]

In [21]:
reaction_times2

array([437., 392., 438., 336., 396., 361., 354., 330., 366., 414., 449.,
       383., 398., 372., 410.])

In [22]:
reaction_times3

array([ 2709., 19726.,   374.,   370.,  4917.,   262.,   296.,   720.,
         491.,   416.,   301.,   225.,   283.,   292.,   287.])

In [39]:
vera = reaction_times2

In [40]:
vera

array([437., 392., 438., 336., 396., 361., 354., 330., 366., 414., 449.,
       383., 398., 372., 410.])

In [42]:
kilian = reaction_times

In [43]:
kilian

[598, 346, 320, 265, 281, 281, 297, 394, 321, 298, 264, 334, 260, 279, 249]

In [44]:
paula = reaction_times3

In [45]:
paula

array([ 2709., 19726.,   374.,   370.,  4917.,   262.,   296.,   720.,
         491.,   416.,   301.,   225.,   283.,   292.,   287.])

Stats 1:

In [27]:
from scipy import stats

In [46]:
stats.ranksums(kilian, vera)

RanksumsResult(statistic=-3.5878528637672713, pvalue=0.00033341234141853304)

Stats 2:

In [47]:
stats.ansari(kilian, vera)

AnsariResult(statistic=104.0, pvalue=0.1834812786386809)

Stats 3:

In [48]:
stats.shapiro(paula)

ShapiroResult(statistic=0.42615342140197754, pvalue=9.438223855795513e-07)

In [49]:
stats.f_oneway(kilian, paula)

F_onewayResult(statistic=1.896550641021259, pvalue=0.1793758008564158)

In [50]:
stats.f_oneway(kilian)

TypeError: at least two inputs are required; got 1.

In [51]:
stats.f_oneway(paula, vera, kilian)

F_onewayResult(statistic=1.8253348701171803, pvalue=0.1737180221198992)

In [52]:
stats.binom?

Signature:       stats.binom(*args, **kwds)
Type:            binom_gen
String form:     <scipy.stats._discrete_distns.binom_gen object at 0x7f9dea39f910>
File:            ~/opt/anaconda3/lib/python3.8/site-packages/scipy/stats/_discrete_distns.py
Docstring:      
A binomial discrete random variable.

As an instance of the `rv_discrete` class, `binom` object inherits from it
a collection of generic methods (see below for the full list),
and completes them with details specific for this particular distribution.

Methods
-------
rvs(n, p, loc=0, size=1, random_state=None)
    Random variates.
pmf(k, n, p, loc=0)
    Probability mass function.
logpmf(k, n, p, loc=0)
    Log of the probability mass function.
cdf(k, n, p, loc=0)
    Cumulative distribution function.
logcdf(k, n, p, loc=0)
    Log of the cumulative distribution function.
sf(k, n, p, loc=0)
    Survival function  (also defined as ``1 - cdf``, but `sf` is sometimes more accurate).
logsf(k, n, p, loc=0)
    Log of the survival f